root: true
env:
  node: true
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
  - prettier
rules:
  vue/multi-word-component-names: 'off'
  prettier/prettier: warn
